version: '3.3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "80:8000"
    links:
      - redis:redis
    environment: 
      - DEBUG=1
      - SECRET_KEY=foo
      - CACHE_LOCATION=redis://redis:6379
  celery:
    build: .
    command: celery -A zaba worker -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A zaba beat -l info
    volumes:
      - .:/usr/src/app/
    depends_on:
      - redis
  celery-flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    depends_on:
        - redis
  redisinsight:
    image: redislabs/redisinsight
    restart: always
    volumes:
      - redisinsight:/db
    ports:
      - "8001:8001"
    links:
      - redis:redis
    depends_on:
      - redis
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata:
  redisinsight:
